/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm") version "1.9.21"
    `java-library`
}

repositories {
    mavenCentral()
}


dependencies {
    implementation(libs.com.google.guava.guava)
    implementation(libs.ch.qos.logback.logback.classic)
    testImplementation(libs.junit.junit)
    testImplementation(kotlin("test"))
}

group = "org.nhnnext"
version = "1.0"
description = "web-application-server"
java.sourceCompatibility = JavaVersion.VERSION_17

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.test { // See 5️⃣
    useJUnitPlatform() // JUnitPlatform for tests. See 6️⃣
}
kotlin {
    jvmToolchain(17)
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
