/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
}

repositories {
    mavenCentral()
}


dependencies {
    implementation(libs.com.google.guava.guava)
    implementation(libs.ch.qos.logback.logback.classic)
    testImplementation(libs.junit.junit)
}

group = "org.nhnnext"
version = "1.0"
description = "web-application-server"
java.sourceCompatibility = JavaVersion.VERSION_17

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
